version: "2"
linters:
  default: all
  disable:
    # unwanted
    - depguard
    - dupl
    - ireturn
    - noinlineerr
    - paralleltest
    - varnamelen
    - wsl
    - wsl_v5
  settings:
    govet:
      enable-all: true
    revive:
      enable-default-rules: true
      rules:
        # additionals
        - name: confusing-naming
        - name: import-alias-naming
        - name: import-shadowing
        - name: unhandled-error
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - funlen
          - goconst
          - prealloc
        path: (.+)_test\.go$
      - linters:
          - revive
        path: (.+)/example_test\.go$
    paths:
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
