linters:
  enable-all: true
  disable:
    # maligned # deprecated 1.38 but govet-fieldalignment not usuable
    - interfacer # deprecated 1.38
    - scopelint # deprecated 1.39
    - golint # deprecated 1.41
    - wsl
    - exhaustivestruct
    - paralleltest
    - varnamelen
    - dupl
    - ireturn
linters-settings:
  govet:
    enable-all: true
issues:
  exclude-rules:
    - path: '(.+)_test\.go'
      linters:
        - funlen
        - goconst
