name: Go Tests
on: [push, pull_request]
jobs:
  test-1_21:
    name: Test 1.21
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.21
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
        id: go
      - name: Check out code
        uses: actions/checkout@v4
      - name: Test
        run: go test -v ./...

  test-1_22:
    name: Test 1.22
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.22
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
        id: go
      - name: Check out code
        uses: actions/checkout@v4
      - name: Test
        run: go test -v ./...

  test-1_23:
    name: Test 1.23
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.23
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
        id: go
      - name: Check out code
        uses: actions/checkout@v4
      - name: Test
        run: go test -v ./... -coverprofile=coverage.out -covermode=atomic 

      - name: Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.out
