name: GolangCI-Lint
on: [push, pull_request]
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'
        id: go
      - name: Check out code
        uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50
          args: -c .golangci.yml -v
